"""edit model

Revision ID: 761eb8fcdfa9
Revises: b2749a7053dc
Create Date: 2025-04-10 16:32:51.982103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761eb8fcdfa9'
down_revision: Union[str, None] = 'b2749a7053dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('team_name', sa.String(), nullable=False))
    op.add_column('meetings', sa.Column('department_name', sa.String(), nullable=False))
    op.drop_column('meetings', 'team_id')
    op.drop_column('meetings', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('meetings', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('meetings', 'department_name')
    op.drop_column('meetings', 'team_name')
    # ### end Alembic commands ###
